name: Pull Request Discord Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Permite acceder al código del repositorio

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new pull request has been created in {{ github.repository }} by {{ github.actor }}. Check it out: {{ github.event.pull_request.html_url }}'
